FROM ros_docker

SHELL [ "/bin/bash" , "-c" ]

ARG PROJECT_NAME=autonomous_rc_model_car

# Upgrade all packages
RUN apt-get update && apt-get upgrade -y

# Install essential packages
RUN apt-get install -y wget \
    git tmux

# Copy tmux configurations
COPY tmux.conf /root/.tmux.conf

# Set environment variables
ENV ROS_DOMAIN_ID=21
ENV GZ_SIM_RESOURCE_PATH=/ros_ws/src/${PROJECT_NAME}/src/
ENV GIT_DIR=/ros_ws/src/${PROJECT_NAME}/.git
ENV GIT_WORK_TREE=/ros_ws/src/${PROJECT_NAME}

# Create overlay workspace
WORKDIR /ros_ws/src
COPY .devcontainer/packages.repos .

# Copy source code into the container if the project is fix
# COPY . /ros_ws/src/${PROJECT_NAME}

RUN vcs import < packages.repos; \
    cd ..; \
    apt-get update; \
    rosdep update; \
    rosdep install --from-paths src --ignore-src -r -y; \
    source /opt/ros/${ROS_DISTRO}/setup.bash; \
    colcon build;

# Add sourcing overlay to .bashrc
RUN echo "source /opt/ros/$ROS_DISTRO/setup.bash" >> ~/.bashrc; \
    echo "source /ros_ws/install/setup.bash" >> ~/.bashrc; \
    echo "source /usr/share/bash-completion/completions/git" >> ~/.bashrc; \
    git config --global --add safe.directory ${GIT_WORK_TREE}

# Set initial dir for container
WORKDIR /ros_ws

# Set up tmux session
CMD ["bash", "-c", "tmux new-session -s ros-control-desk -d bash; tmux split-window -h; tmux split-window -v; tmux select-pane -t 0; tmux split-window -v; tmux attach"]
