FROM ros_docker

SHELL ["/bin/bash", "-c"]

ARG PROJECT_NAME=athena-race-stack

RUN sed -i 's|^deb .*packages.ros.org|# &|g' /etc/apt/sources.list || true \
 && sed -i 's|^deb .*packages.ros.org|# &|g' /etc/apt/sources.list.d/*.list || true \
 && sed -i 's|^URIs:.*packages.ros.org|# &|g' /etc/apt/sources.list.d/*.sources || true

RUN apt-get update && apt-get install -y --no-install-recommends \
    ca-certificates \
    curl \
    gnupg \
 && rm -rf /var/lib/apt/lists/*

RUN mkdir -p /etc/apt/keyrings \
 && curl -fsSL https://raw.githubusercontent.com/ros/rosdistro/master/ros.key \
    | gpg --dearmor -o /etc/apt/keyrings/ros-archive-keyring.gpg

RUN echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/ros-archive-keyring.gpg] \
http://packages.ros.org/ros2/ubuntu noble main" \
> /etc/apt/sources.list.d/ros2.list

RUN apt-get update && apt-get upgrade -y

RUN apt-get install -y --no-install-recommends \
    wget \
    git \
    tmux \
    python3-rosdep

COPY docker/tmux.conf /root/.tmux.conf

ENV ROS_DOMAIN_ID=21
ENV GZ_SIM_RESOURCE_PATH=/ros_ws/src/${PROJECT_NAME}/src/
ENV GIT_DIR=/ros_ws/src/${PROJECT_NAME}/.git
ENV GIT_WORK_TREE=/ros_ws/src/${PROJECT_NAME}

WORKDIR /ros_ws

RUN rm -rf /ros_ws/src \
 && mkdir -p /ros_ws/src

COPY ros2.repos /ros_ws/

RUN vcs import --skip-existing /ros_ws/src < /ros_ws/ros2.repos \
 && rosdep update \
 && rosdep install --from-paths /ros_ws/src --ignore-src -r -y \
 && source /opt/ros/${ROS_DISTRO}/setup.bash \
 && colcon build

RUN echo "source /opt/ros/$ROS_DISTRO/setup.bash" >> /root/.bashrc \
 && echo "source /ros_ws/install/setup.bash" >> /root/.bashrc \
 && echo "source /usr/share/bash-completion/completions/git" >> /root/.bashrc \
 && git config --global --add safe.directory ${GIT_WORK_TREE}

WORKDIR /ros_ws

CMD ["bash", "-c", "tmux new-session -s ros-control-desk -d bash; tmux split-window -h; tmux split-window -v; tmux select-pane -t 0; tmux split-window -v; tmux attach"]
