FROM ros:jazzy-ros-base

SHELL ["/bin/bash", "-c"]

ARG PROJECT_NAME=athena-race-stack

# -----------------------------
# System Update
# -----------------------------
RUN apt-get update && apt-get upgrade -y

# -----------------------------
# Base Tools
# -----------------------------
RUN apt-get install -y --no-install-recommends \
    wget \
    git \
    tmux \
    python3-rosdep \
    python3-pip \
    libasio-dev

# -----------------------------
# Raspberry Pi 5 NeoPixel Support
# -----------------------------
RUN pip3 install --break-system-packages pi5neo
RUN pip install adafruit-blinka adafruit-circuitpython-neopixel adafruit-circuitpython-pixelbuf lgpio --break-system-packages
RUN pip install Adafruit-Blinka-Raspberry-Pi5-Neopixel --break-system-packages

# -----------------------------
# Workspace Setup
# -----------------------------
ENV ROS_DOMAIN_ID=21
ENV GZ_SIM_RESOURCE_PATH=/ros_ws/src/${PROJECT_NAME}/src/

WORKDIR /ros_ws
RUN mkdir -p src

COPY ros2.repos /ros_ws/ros2.repos

# -----------------------------
# Import & Build
# -----------------------------
RUN vcs import src < ros2.repos \
 && rosdep update \
 && rosdep install --from-paths src --ignore-src -r -y \
 && source /opt/ros/${ROS_DISTRO}/setup.bash \
 && colcon build

# -----------------------------
# Bash Environment
# -----------------------------
RUN echo "source /opt/ros/$ROS_DISTRO/setup.bash" >> /root/.bashrc \
 && echo "source /ros_ws/install/setup.bash" >> /root/.bashrc

CMD ["bash"]
